# Generated by Django 5.2.1 on 2025-05-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_author_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
    ]
