# Generated by Django 5.2.1 on 2025-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_num',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار'),
        ),
    ]
