# Generated by Django 5.2.1 on 2025-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_book_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
    ]
