# Generated by Django 5.2.1 on 2025-07-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.book', verbose_name='کتاب'),
        ),
    ]
